namespace: businessproject
resources:
  - namespace.yaml
  - mysql/secret.yaml
  - mysql/pvc.yaml
  - mysql/deployment.yaml
  - mysql/service.yaml
  - app/configmap.yaml
  - app/deployment.yaml
  - app/service.yaml