apiVersion: v1
kind: Service
metadata:
  name: business-app
  namespace: businessproject
spec:
  ports:
    - port: 9191
      targetPort: 2330
      nodePort: 32191 
  selector:
    app: business-app
  type: NodePort   # or NodePort if no LB available
